export const GEOIP_COUNTRY_OPTIONS = [
    { code: 'KR', name: '한국', flag: '🇰🇷' },
    { code: 'US', name: '미국', flag: '🇺🇸' },
    { code: 'JP', name: '일본', flag: '🇯🇵' },
    { code: 'CN', name: '중국', flag: '🇨🇳' },
    { code: 'GB', name: '영국', flag: '🇬🇧' },
    { code: 'DE', name: '독일', flag: '🇩🇪' },
    { code: 'FR', name: '프랑스', flag: '🇫🇷' },
    { code: 'CA', name: '캐나다', flag: '🇨🇦' },
    { code: 'AU', name: '호주', flag: '🇦🇺' },
    { code: 'RU', name: '러시아', flag: '🇷🇺' },
    { code: 'BR', name: '브라질', flag: '🇧🇷' },
    { code: 'IN', name: '인도', flag: '🇮🇳' },
    { code: 'SG', name: '싱가포르', flag: '🇸🇬' },
    { code: 'TW', name: '대만', flag: '🇹🇼' },
    { code: 'HK', name: '홍콩', flag: '🇭🇰' },
    { code: 'TH', name: '태국', flag: '🇹🇭' },
    { code: 'VN', name: '베트남', flag: '🇻🇳' },
    { code: 'ID', name: '인도네시아', flag: '🇮🇩' },
    { code: 'MY', name: '말레이시아', flag: '🇲🇾' },
    { code: 'PH', name: '필리핀', flag: '🇵🇭' }
];
